server.port: 8083
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/demo
    username: demo
    password: demo
  sql.init.mode: always
management.endpoints.web.exposure.include: health
